### ISSUE TITLE
Any plans to release other models?

### ISSUE THREAD

**Issue by tealgreen0503** [nttcslab/japanese-dialog-transformers#3]
Thank you for the great chat-bot models and datasets.

Do you have any plans to release trained models for other sizes (0.3B, 0.7B and 1.1B)?  Also, do you have any plans to release models trained on mixed datasets?

In particular, I think the smaller size models are useful for fine-tuning by people who do not have enough computation resources (like me).

Thank you in advance.

**Comment by h-sugi** [comment]
Thank you for the comment. We also think the smaller size models are useful to examine the effect of model size, so we have a plan to release other size models. But unfortunately, we don't plan to release the models trained with the mixed dataset and the FavoriteThingsChat dataset for the time being.

**Comment by tealgreen0503** [comment]
Thank you for your reply.
I am looking forward to the smaller size models!
